const shortcutMap = {
  // 打开链接
  'ctrl+l': 'open-link',
  // 打开AI
  'ctrl+k': 'open-ai',
  // 打开引用
  'ctrl+q': 'open-quote',
  // 复制
  'ctrl+c': 'copy',
  // 粘贴
  'ctrl+v': 'paste',
  // 剪切
  'ctrl+x': 'cut',
  // 撤销
  'ctrl+z': 'undo',
  // 重做
  'ctrl+shift+z': 'redo',
  // 保存
  'ctrl+s': 'save',
  // 打开设置
  'ctrl+i': 'open-settings',
  // 打开帮助
  'ctrl+h': 'open-help',
  // 打开关于
  'ctrl+a': 'open-about',
  // 搜索
  'ctrl+f': 'search',
  // 全局搜索
  'ctrl+shift+f': 'global-search',
};
